nea/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.account_page, name='account_page'),
    path('comments/', views.comments_page, name='comments_page'),
    path('favourites/', views.favourites_page, name='favourites_page'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('planner/', views.planner_page, name='planner_page'),
    path('planner/<str:last_date>/', views.planner_page, name='planner_page'),
    path('planner/add/<int:add_days>/', views.planner_page, name='planner_page'),
    path('planner/<str:last_date>/add/<int:add_days>/', views.planner_page, name='planner_page'),
    path('planner/remove/<int:plannermeal_id>/', views.planner_remove, name='planner_page'),
    path('planner/remove/<str:last_date>/<int:plannermeal_id>/', views.planner_remove, name='planner_page'),
    path('add_favourite/<int:meal_pk>/<path:goto>/', views.add_favourite, name='add_favourite'),
    path('edit_comment/<str:comment_type>/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('delete_comment/<str:comment_type>/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

nea/nea/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('welcome.urls', 'welcome'), namespace='welcome')),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('meal/', include(('meal.urls', 'meal'), namespace='meal')),
    path('search/', include(('search.urls', 'search'), namespace='search')),
    path('admin/', admin.site.urls),
]

nea/search/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.search_page, name='search_page'),
    path('results/<str:search_term>/', views.search_results, name='search_results'),
]

nea/welcome/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
]

nea/templates/partials/_footer.html
<nav class="footer" style="background-color: #e3f2fd;">
    <div class="container p-2 pb-4">
        <div class="navbar-nav text-center">
            <div class="row">
                <span class="col navbar-brand active text-left" href="#">Created by Layton Burchell</span>
            </div>
            <div class="row">
                <a class="text-muted col" href="https://github.com/LaytonGB" target="_blank">GitHub</a>
                <a class="text-muted col" href="https://gitlab.com/LaytonGB" target="_blank">GitLab</a>
                <a class="text-muted col" href="{% url 'welcome:about' %}">About</a>
            </div>
        </div>
    </div>
</nav>

nea/templates/partials/_navbar.html
<nav class="navbar navbar-expand navbar-dark bg-primary mb-4">
    <div class="container">
        <a href="{% url 'welcome:home' %}" class="navbar-brand">Meal Master</a>
        <div class="navbar-nav">
            <a href="{% url 'search:search_page' %}" class="nav-link active">Search<span class="sr-only">(current)</span></a>
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:account_page' %}" class="nav-link active">Profile</a>
                <a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a>
            {% else %}
                <a href="{% url 'accounts:login' %}" class="nav-link active">Login or Register</a>
            {% endif %}
        </div>
    </div>
</nav>