nea/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.account_page, name='account_page'),
    path('comments/', views.comments_page, name='comments_page'),
    path('favourites/', views.favourites_page, name='favourites_page'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('planner/', views.planner_page, name='planner_page'),
    path('planner/<str:last_date>/', views.planner_page, name='planner_page'),
    path('planner/add/<int:add_days>/', views.planner_page, name='planner_page'),
    path('planner/<str:last_date>/add/<int:add_days>/', views.planner_page, name='planner_page'),
    path('planner/remove/<int:plannermeal_id>/', views.planner_remove, name='planner_page'),
    path('planner/remove/<str:last_date>/<int:plannermeal_id>/', views.planner_remove, name='planner_page'),
    path('add_favourite/<int:meal_pk>/<path:goto>/', views.add_favourite, name='add_favourite'),
    path('edit_comment/<str:comment_type>/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('delete_comment/<str:comment_type>/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

nea/meal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:meal_id>/', views.meal_page, name='meal_page'),
    path('<int:meal_id>/comment/', views.comment, name='comment'),
    path('<int:meal_id>/rate/comment/<int:comment_id>/', views.submit_comment_rating, name='submit_comment_rating'),
    path('<int:meal_id>/rate/subcomment/<int:step_id>/<int:subcomment_id>/', views.submit_subcomment_rating, name='submit_subcomment_rating'),
    path('<int:meal_id>/rate/<str:rating_section_name>/', views.submit_meal_rating, name='submit_meal_rating'),
    path('<int:meal_id>/subcomment/<int:step_id>/', views.subcomment, name='subcomment'),
    path('<int:meal_id>/<str:focus>/', views.meal_page, name='meal_page'),
    path('<int:meal_id>/<str:focus>/<int:step_id>/', views.meal_page, name='meal_page'),
    path('<int:meal_id>/<int:step_id>/', views.meal_page, name='meal_page_subcomment'),
]

nea/nea/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('welcome.urls', 'welcome'), namespace='welcome')),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('meal/', include(('meal.urls', 'meal'), namespace='meal')),
    path('search/', include(('search.urls', 'search'), namespace='search')),
    path('admin/', admin.site.urls),
]

nea/accounts/models.py
from meal.models import Meal
from django.db import models

from django.contrib.auth.models import User
from django.db.models.aggregates import Max

# Customize the string representation of users
def name(self):
    return f'(ID: {self.id}) User "{self.username}"'

User.add_to_class("__str__", name)

# Users planner model
class PlannerManager(models.Manager):
    def create_planner(self, user):
        planner = self.create(
            user = user,
        )
        return planner
class Planner(models.Model):
    user = models.OneToOneField(User, verbose_name="Meal Planner", on_delete=models.CASCADE)
    def __str__(self):
        return f'(Planner ID: {self.id}) {self.user}\'s Meal Plan'
    class Meta:
        ordering = ('pk',)
    objects = PlannerManager()

class PlannerMealManager(models.Manager):
    def create_plannermeal(self, planner, date, meal, highest_order, custom_meal=None):
        planner_meal = self.create(
            planner = planner,
            date = date,
            meal = meal,
            order = highest_order + 1,
            custom_meal = custom_meal,
        )
        return planner_meal
    def get_highest_order(self, id):
        pm = self.get(id=id) # pm=plannermeal
        return self.filter(date=pm.date).aggregate(order_max=Max('order')).get('order_max') or 0
    def adjust_order(self, x, id):
        # x=new_order y=old_order id=plannermeal_id z=selected_plannermeal
        y = None
        z = None
        try:
            z = self.get(id=id)
            y = z.order
        except:
            pass
        if (not z) or (x is y):
            return
        z.order = self.get_highest_order(id) + 1
        z.save()
        meals_to_modify = None
        a = None # a=adjustment_value
        if x > y:
            meals_to_modify = self.filter(date=z.date).filter(order__gte=y).order_by('order') # plannermeals y or greater
            a = -1
        elif x < y:
            meals_to_modify = self.filter(date=z.date).filter(order__gte=x).order_by('order') # plannermeals x or greater
            a = +1
        for m in meals_to_modify:
            m.order = m.order + a
            m.save()
        z.order = x
        z.save()
class PlannerMeal(models.Model):
    planner = models.ForeignKey(Planner, on_delete=models.CASCADE, related_name='meals')
    date = models.DateField(null=False)
    order = models.IntegerField(unique_for_date='date')
    meal = models.ForeignKey(Meal, verbose_name="Meal(s) in Planner on this Day", related_name='plannermention', on_delete=models.CASCADE, default=1, null=True)
    custom_meal = models.CharField(max_length=40, blank=True, null=True)
    def __str__(self):
        return f'(Planner Meal ID: {self.id}) {self.meal} on {self.date} in {self.planner}'
    class Meta:
        ordering = ('date','order',)
    objects = PlannerMealManager()

nea/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from meal.forms import CommentCreationForm

class CreateUserForm(UserCreationForm):
    password1 = forms.CharField(
        label=('Password'),
        strip=False,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password',})
    )
    password2 = forms.CharField(
        label=('Confirm Password'),
        strip=False,
        widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Confirm Password',})
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username',}),
            'email': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email',}),
        }

class CommentEditForm(forms.Form):
    content = forms.CharField(
        label = 'CommentArea',
        widget = forms.TextInput(attrs={
            'class':'form-control',
            'id':'comment_input',
            'placeholder':'Leave a comment',
        }),
    )

nea/accounts/views.py
from django.db.models.aggregates import Max
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from itertools import chain
from operator import attrgetter

from django.utils import timezone
from django.utils.dateparse import parse_date
from datetime import datetime, timedelta

from .forms import CreateUserForm, CommentEditForm
from meal.models import Meal, MealComment, SubComment
from .models import Planner, PlannerMeal

def account_page(request):
    context = {'page_title':'My Account',}

    if request.user.is_authenticated:
        return render(request, 'accounts/user_account.html', context)
    else:
        return redirect('/account/login')

def comments_page(request):
    if request.user.is_authenticated:
        user = request.user
        mealcomments = user.mealcomment.all()
        subcomments = user.subcomment.all()
        if mealcomments and subcomments:
            comments = list(mealcomments) + list(subcomments)
            comments.sort(key=lambda a: a.date)
        elif mealcomments:
            comments = mealcomments
        elif subcomments:
            comments = subcomments
        else:
            comments = None

        context = {
            'page_title':'My Comments',
            'user':user,
            'comments':comments,
        }
        return render(request, 'accounts/user_comments.html', context)
    else:
        return redirect('/account/login')

def favourites_page(request):
    if not request.user.is_authenticated:
        return redirect('/account/login')
    user = request.user
    favourites_query = list(user.meal_set.all())
    favourites_list = []
    for f in favourites_query:
        try:
            rating_section = f.ratingsection.get(name='overall')
            meal_rating = rating_section.get_rating()
            rating_count = rating_section.rating_count()
        except:
            rating_count = 0
            meal_rating = -1
        favourites_list.append({
            'id':f.id,
            'name':f.name,
            'description':f.description,
            'rating_count':rating_count,
            'rating':meal_rating,
        })
    context = {
        'page_title':'Favourites',
        'user':user,
        'favourites':favourites_list,
    }
    return render(request, 'accounts/user_favourites.html', context)

def planner_page(request, last_date='', add_days=0):
    user = request.user

    if not user.is_authenticated:
        return redirect('/account/login')

    # set date to user input if there is any, else today
    last_date_parsed = None
    if last_date:
        last_date_parsed = datetime.strptime(last_date, "%d-%m-%Y").date()
    date = last_date_parsed or timezone.now()
    userdate = request.GET.get('submitted_date')
    if userdate:
        # this kind of parsing only works because the date is supplied straight from a HTML calendar
        date = parse_date(userdate)
        last_date = datetime.strftime(date, "%d-%m-%Y")
        if last_date:
            return redirect(f'/account/planner/{last_date}')
        return redirect('/account/planner/')

    # if a meal needs to be added, add it to the specific day
    # then reload this view
    data = request.GET.get('add_meal')
    if data:
        parts = data.split()
        sub_date = datetime.strptime(parts[0], "%d-%m-%Y").date()
        meal_id = parts[1]
        meal = Meal.objects.get(id=meal_id)
        if meal:
            order = PlannerMeal.objects.filter(date=sub_date).aggregate(order_max=Max('order')).get('order_max') or 0
            PlannerMeal.objects.create_plannermeal(user.planner, sub_date, meal, order)
        if last_date:
            return redirect(f'/account/planner/{last_date}')
        return redirect('/account/planner/')

    # if a custom meal needs to be added, add it to the specific day
    # then reload this view
    data = request.GET.get('custom_meal_name')
    if data:
        add_date_parsed = date + timedelta(days=add_days)
        order = PlannerMeal.objects.filter(date=add_date_parsed).aggregate(order_max=Max('order')).get('order_max') or 0
        PlannerMeal.objects.create_plannermeal(user.planner, add_date_parsed, None, order, data)
        if last_date:
            return redirect(f'/account/planner/{last_date}')
        return redirect('/account/planner/')

    # if a meal order is to be changed, change it
    # then reload this view
    data = request.GET.get('change_meal_order')
    if data:
        parts = data.split()
        new_order = int(parts[0])
        plannermeal_id = int(parts[1])
        if plannermeal_id and new_order:
            PlannerMeal.objects.adjust_order(new_order, plannermeal_id)
        else:
            messages.warning(request, 'Could not change meal order.')
        if last_date:
            return redirect(f'/account/planner/{last_date}')
        return redirect('/account/planner/')

    # get user favourites
    faves = user.meal_set.all()
    favourites = []
    for f in faves:
        favourites.append({
            'id':f.id,
            'name':f.name,
            'description':f.description,
            'rating':f.ratingsection.get(name='overall').get_rating(),
            'rating_count':f.ratingsection.get(name='overall').rating_count(),
        })

    # if user does not have a planner, create one
    try:
        user.planner
    except:
        Planner.objects.create_planner(user)

    # get meals from user planner and add them to the necessary days
    planner = []
    dates = []
    for i in range(0, 7): # for each day
        day = []
        this_date = date + timedelta(days=i)
        dates.append(this_date)
        meals = user.planner.meals.filter(date=this_date).order_by('order')
        if meals:
            for m in meals: # for each mealplan_meal
                # try and add the meal as a proper meal. if the meal is custom, this will cause an error
                # in which case, add the meal as a custom meal
                try:
                    day.append({
                        'id':m.id,
                        'order':m.order,
                        'meal_id':m.meal.id,
                        'name':m.meal.name,
                        'description':m.meal.description,
                        'rating':m.meal.ratingsection.get(name='overall').get_rating(),
                        'rating_count':m.meal.ratingsection.get(name='overall').rating_count(),
                    })
                except:
                    day.append({
                        'id':m.id,
                        'order':m.order,
                        'meal_id':-1,
                        'name':m.custom_meal,
                        'description':'',
                        'rating':-1,
                        'rating_count':-1,
                    })
        planner.append(day)

    context = {
        'page_title':'Meal Planner',
        'user':request.user,
        'date':date,
        'planner':planner,
        'dates':dates,
        'favourites':favourites,
        'last_date':last_date,
    }
    return render(request, 'accounts/meal_planner.html', context)

def planner_remove(request, plannermeal_id, last_date=''):
    if plannermeal_id:
        PlannerMeal.objects.get(id=plannermeal_id).delete()
    else:
        messages.warning(request, 'Could not remove meal.')
    if last_date:
        return redirect(f'/account/planner/{last_date}')
    return redirect('/account/planner/')

def delete_comment(request, comment_type, comment_id):
    if request.user.is_authenticated:
        if comment_type == 'mealcomment':
            comment = MealComment.objects.get(pk=comment_id)
        elif comment_type == 'subcomment':
            comment = SubComment.objects.get(pk=comment_id)
        else:
            messages.error(request, 'Comment could not be found.')
            return redirect('/account/comments')
        user = request.user
        if user == comment.user:
            comment.delete()
            messages.success(request, 'Comment deleted.')
            return redirect('/account/comments')
        else:
            return redirect('/account/login')

    else:
        return redirect('/account/login')

def edit_comment(request, comment_type, comment_id):
    if comment_type == 'mealcomment':
        comment = MealComment.objects.get(pk=comment_id)
    elif comment_type == 'subcomment':
        comment = SubComment.objects.get(pk=comment_id)
    else:
        messages.error(request, 'Comment could not be found.')
        return redirect('/account/comments')

    user = request.user
    if request.method == 'POST':
        new_content = request.POST.get('content')
        comment.content = new_content
        comment.save()
        messages.success(request, 'Comment has been edited.')
        return redirect('/account/comments')

    elif user.is_authenticated:
        if user == comment.user:
            form = CommentEditForm()
            context = {
                'form':form,
                'page_title':'Edit Comment',
                'comment':comment,
                'user':user,
            }
            return render(request, 'accounts/edit_comment.html', context)
        else:
            return redirect('/account/login')

    else:
        return redirect('/account/login')

def add_favourite(request, meal_pk, goto):
    if request.method == 'POST':
        try:
            user = request.user
            meal = Meal.objects.get(pk=meal_pk)
            if meal.favourites.filter(id=user.id).first():
                meal.favourites.remove(user)
            else:
                meal.favourites.add(user)
        except:
            messages.warning(request, 'Could not add favourite.')
    # redirect to previous page
    return redirect(goto)

def login_page(request):
    form = CreateUserForm()
    context = {'page_title':'Login or Register', 'form':form,}

    if request.method == "POST":

nea/templates/accounts/edit_comment.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Edit Comment</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <div class="row">
                <div class="container">
                    {{ form.content }}
                </div>
            </div>
            <div class="row">
                <div class="container justify-content-end text-right my-1">
                    <input type="submit" value="Update Comment" class="form-control btn btn-primary col-auto">
                </div>
            </div>
        </div>
    </form>
</div>

<script type='text/javascript'>
    const oldComment = '{% filter escapejs %}{{ comment.content }}{% endfilter %}';
    const commentInput = document.getElementById('comment_input');
    commentInput.value = oldComment;
</script>
{% endblock content %}

nea/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col text-center login-half">
                <h1>Login</h1>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="container text-center col-10">
                        <div class="form-group">
                            <input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
                        </div>
                        <div class="form-group">
                            <input type="password" name="password" class="form-control" placeholder="Password" required>
                        </div>
                    </div>
                    <br>
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.level_tag == 'error' %}
                                <div class="container border border-danger text-danger text-center rounded">
                                    <p class="p-2 m-auto">{{ message }}</p>
                                </div>
                                <br>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                    <div class="container text-right col-10">
                        <input type="submit" value="Login" name="login" class="btn btn-primary">
                    </div>
                </form>
            </div>
            <div class="d-lg-none w-100 border-top my-4"></div>
            <div class="col text-center justify-content-end">
                <h1>Register</h1>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="container text-center col-10">
                        <div class="form-group">
                            {{form.username}}
                        </div>
                        <div class="form-group">
                            {{form.email}}
                        </div>
                        <div class="form-group">
                            {{form.password1}}
                        </div>
                        <div class="form-group">
                            {{form.password2}}
                        </div>
                    </div>
                    {% if form.errors %}
                        <div class="container text-danger border-danger border rounded text-left">
                            {% for field in form %}
                                {% if field.errors %}
                                    <p>
                                        <strong>{{ field.label|capfirst }}</strong>
                                        <ul>
                                            {% for error in field.errors %}
                                                <li>{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    </p>
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    <br>
                    <div class="container text-right col-10">
                        <input type="submit" value="Submit" name="register" class="btn btn-primary">
                    </div>
                </form>
            </div>
            {% if messages %}
                {% for message in messages %}
                    {% if message.level_tag == 'success' %}
                        <div class="container border border-success text-success text-center rounded p">
                            <p class="p-2 m-auto">{{ message }}</p>
                        </div>
                        <br>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

nea/templates/accounts/user_account.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>My Account</h1>
        <a href="favourites/" class="btn btn-warning">Favourites</a>
        <a href="planner/" class="btn btn-danger">Meal Planner</a>
        <a href="comments/" class="btn btn-primary">Comments</a>
        <a href="#" class="btn btn-info">Preferences</a>
    </div>
{% endblock content %}

nea/templates/accounts/user_comments.html
{% extends 'base.html' %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.level_tag == 'success' %}
                <div class="container border border-success text-success text-center rounded">
                    <p class="p-2 m-auto text-capitalize">{{ message }}</p>
                </div>
                <br>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="container">
        <h1 class="mb-3">My Comments</h1>
        {% if comments %}
            {% for comment in comments reversed %}
                <div class="row">
                    <div class="container col border border-warning rounded my-3 px-4">
                        <div class="row border-bottom font-weight-bold justify-content-between">
                            <div>
                            {% if comment.c_name in 'mealcomment' %}
                                {% with comment.id|stringformat:'s' as comment_id %}
                                    <a href="{% url 'meal:meal_page' meal_id=comment.meal.id focus='comment_'|add:comment_id %}" class="text-info">
                                        {{ comment.meal.name }}
                                {% endwith %}
                            {% else %}
                                <a href="{% url 'meal:meal_page_subcomment' meal_id=comment.parent.section.meal.id step_id=comment.parent.id %}" class="text-info">
                                    {{ comment.parent.section.meal.name }}
                            {% endif %}</a>
                            </div>
                            <div>{{ comment.date }}</div>
                        </div>
                        <div class="row my-1">
                            {{ comment.content }}
                        </div>
                        <div class="row border-top text-muted justify-content-around">
                            <div><a href="{% url 'accounts:delete_comment' comment_type=comment.c_name comment_id=comment.pk %}" class="text-reset">Delete Comment</a></div>
                            <div><a href="{% url 'accounts:edit_comment' comment_type=comment.c_name comment_id=comment.pk %}" class="text-reset">Edit Comment</a></div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>You haven't left any comments yet. Try leaving one!</p>
        {% endif %}
    </div>
{% endblock content %}

nea/templates/accounts/user_favourites.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Favourites</h1>
        <div id="favourites_list" class="col">
            <div class="searchbar">
                <div class="row form-group">
                    <div class="col">
                        <input v-model="search_term" class="form-control" placeholder="Search...">
                    </div>
                </div>
            </div>
            {% comment %} for each favourite {% endcomment %}
            <div v-for="(f, i) in filtered_favourites" class="py-1">
                {% comment %} the button links to the href here, where ${f.id} is the favourite id {% endcomment %}
                <a
                    :href="`/meal/${f.id}/`"
                    class="w-100 text-left btn btn-info"
                >
                    <div class="row">
                        <h3 class="col align-self-center mt-0">
                            [[ f.name ]]
                        </h3>
                        {% comment %} only show star rating if the meal has been rated {% endcomment %}
                        <h2
                            v-if="f.rating_count > 0"
                            class="rating-display px-3"
                        >
                            {% comment %} display star rating {% endcomment %}
                            <span
                                v-for="star in 5"
                                :class="`text-${star <= f.rating ? 'warning' : 'muted'}`"
                                >★</span
                            >
                        </h2>
                    </div>
                    <p class="mb-0">[[ f.description ]]</p>
                </a>
            </div>
            </div>
        </div>
    </div>

    {% comment %} Vue setup {% endcomment %}
    <script type="text/javascript">
        window.addEventListener('load', () => {
            favourites_vue = new Vue({
                delimiters: ['[[', ']]'],
                el: '#favourites_list',
                data: {
                    favourites: {{ favourites|safe }},
                    search_term: '',
                },
                computed: {
                    filtered_favourites: function () {
                        st = this.search_term;
                        if (st) {
                            return this.favourites.filter(x => {
                                return x.name.includes(st);
                            });
                        } else {
                            return this.favourites;
                        }
                    },
                },
                methods: {},
                watch: {},
                mounted: function () {},
            });
        });
    </script>
{% endblock content %}